### ISSUE TITLE
Can the plugin parse pictures?

### ISSUE THREAD

**Issue by akkuman** [rg-software/wlx-markdown-viewer#1]
I can't see the picture in my markdown file

**Comment by rg-software** [comment]
Send me your markdown, and I'll have a look.

**Comment by akkuman** [comment]
my markdown

```
## Theme Screenshot
![Screenshot_20180820_143859.png](https://i.loli.net/2018/08/20/5b7a62b4ce584.png)
```

pictures do not display correctly.

![image](https://user-images.githubusercontent.com/7813511/57768866-1a560200-773f-11e9-904c-9fa5ffbe7332.png)

**Comment by rg-software** [comment]
Yes, currently the plugin does not support remote screenshots. Perhaps, this can be fixed, but not yet, so let's keep this issue open.

**Comment by akkuman** [comment]
but，I use the local relative path，the picture can't also display
for example
```
![](./img/PADI_TIM_20190512202318.png)
```

**Comment by rg-software** [comment]
Are you sure there are no errors in the code? This fragment works fine on my machine.

**Comment by akkuman** [comment]
no，Typora can parse the picture correctly

**Comment by rg-software** [comment]
Look, I create the file `test.md`, paste your code `![](./img/PADI_TIM_20190512202318.png)` there, and put some image file called `PADI_TIM_20190512202318.png` inside the `img` subfolder. Then I press `F3` under `test.md`, and it works fine. So I can't really reproduce it. Make sure, btw, that `PADI_TIM_20190512202318.png` is indeed a PNG file, not renamed JPG or something like that.

**Comment by akkuman** [comment]
I know the reason. my path contains chinese. I change it to english. it work.
