### ISSUE TITLE
Extended "Table" Syntax Support

### ISSUE THREAD

**Issue by JamoCA** [rg-software/wlx-markdown-viewer#2]
I noticed that the TC plugin doesn't render `tables`.  Are there any plans to add support?
https://www.markdownguide.org/extended-syntax/

## Table Source Example
```
| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |
```

## Table Render Example

| Syntax      | Description |
| ----------- | ----------- |
| Header      | Title       |
| Paragraph   | Text        |

**Comment by rg-software** [comment]
Hi, I'll have a look as soon as I have time. Hopefully in a few days.
The plugin simply calls hoedown library, so I am not completely sure what's implemented there.

**Comment by rg-software** [comment]
I found that tables are actually supported. Open the `MarkdownView.ini` file, find `HoedownArgs=` line and add the `--tables` switch. It should help.

**Comment by mikedepetris** [comment]
Tested, works. Thank you.

**Comment by JamoCA** [comment]
Great!  With the switch added, it renders a table.

I tried different CSS files (none, air, modest, retro, splendor) and none of them were preset to add borders to the table (like GitHub).  I've added this CSS (from GitHub) and it kinda works; the background colors aren't rendered.  A color can be added to the 

Is that a limitation of hoedown or the TC plugin?

```
h1, h2, h3, h4, h5, h6 {background-color:red;} /* this works */

table {
	border-collapse: collapse;
	border-spacing: 0;
	border:1px solid black; /* this works */
}

tr:nth-child(even) {
	background-color: #F6F8FA; /* this doesn't work */
}

td, th {
	padding: 0;
	border-collapse: collapse;
	border:1px solid black; /* this works */
}
```

**Comment by rg-software** [comment]
> Is that a limitation of hoedown or the TC plugin?

I am not 100% sure, but I believe it's a limitation of a severely outdated IE-based HTML viewer, used in the plugin. I am thinking to substitute it with a lightweight alternative (like Sciter), but no firm plans yet.

I agree, rendering isn't quite up to standard, comparing to what we see in Github or VS Code. Maybe it makes sense to update both markdown viewer and html viewer plugins eventually.
