### ISSUE TITLE
about NewWindow

### ISSUE THREAD

**Issue by linwan623910** [rg-software/wlx-markdown-viewer#4]
how to open the link in the newwindow, is that possible?
![pic](https://raw.githubusercontent.com/linwan623910/aaa/master/57eff3fe-ded8-4155-8edb-111dfcc14a4f.gif)

**Comment by rg-software** [comment]
Sorry, no. And I don't think it's easy to implement. This plugin is just a frontend for HTML Viewer, so it can't do much beyond what HTML Viewer can do.
