### ISSUE TITLE
ShowDirs

### ISSUE THREAD

**Issue by wincmd64** [rg-software/wlx-markdown-viewer#5]
```
[options]
; Enables displaying directories in Quick View mode
ShowDirs=1
```

this option doesn't work

**Comment by rg-software** [comment]
Sorry, it isn't supposed to work in markdown mode. Use the original [HTMLView](https://sites.google.com/site/htmlview/) if you need this functionality.

**Comment by wincmd64** [comment]
i use HTMLView only for Ctrl+Q and i dont want have 2 plugins with same functional

**Comment by rg-software** [comment]
I will check how it works. Markdown viewer views markdown files. A directory is not a markdown file, hence, no support :)
