### ISSUE TITLE
Inserted pictures cannot be previewed

### ISSUE THREAD

**Issue by yahuudang** [rg-software/wlx-markdown-viewer#9]
No matter it is a local image or an online image, it cannot be previewed.
![QQ截图20240107221849](https://github.com/rg-software/wlx-markdown-viewer/assets/4756893/e642dfda-f763-41f3-a923-9720678ce211)

**Comment by rg-software** [comment]
You'll have to give more information. This is core functionality, and it works fine for me.
I see you have Chinese there. What is the encoding? Is image file name Latin or Chinese?

**Comment by yahuudang** [comment]
File encoding: UTF8

File content:
```
![img1](assets/001.png)
![img2](assets/002.jpg)
![img3](http://wincmd.ru/files/9924376/markdownscr.png)
```

This picture cannot be previewed. (002.jpg)
![002](https://github.com/rg-software/wlx-markdown-viewer/assets/4756893/98c827d6-77dc-4441-8486-e040b678f710)

I added another 001.png, which can be previewed

![preview](https://github.com/rg-software/wlx-markdown-viewer/assets/4756893/d081a982-ac8a-4f8e-8795-ad5a49853668)

**Comment by yahuudang** [comment]
I found the reason why local pictures cannot be previewed. The file's extension does not match its type.
But it can be accurately previewed in Typora.
Online images still cannot be previewed.

**Comment by yahuudang** [comment]
After modifying the ForceOffline=0, you can preview it and the issue is closed.
